name: x1statmine
version: '${project.version}'
main: ru.x1ndi.x1statmine.X1statmine
api-version: '1.20'
commands:
  statmine-reset:
    description: Сбросить статистику добытых блоков
    usage: /statmine-reset
    permission: statmine.reset

depend: ["PlaceholderAPI"]